trainer:
  max_epochs: 100
  gpus: 1
  strategy: ddp_find_unused_parameters_false
  precision: 16
  callbacks:
  - class_path: pytorch_lightning.callbacks.finetuning_scheduler.FinetuningScheduler
    init_args:
      gen_ft_sched_only: True
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: lightning_logs
      name: dump_test
