0:
  params: # the parameters for each phase definition can be fully specified
  - model.classifier.bias
  - model.classifier.weight
1:
  params: # or specified via a regex
  - model.albert.pooler.*
2:
  params:
  - model.albert.encoder.*.ffn_output.*
3:
  params: # both approaches to parameter specification can be used in the same phase
  - model.albert.encoder.*.(ffn\.|attention|full*).*
  - model.albert.encoder.embedding_hidden_mapping_in.bias
  - model.albert.encoder.embedding_hidden_mapping_in.weight
  - model.albert.embeddings.*
